version: '3'

services:
  nginx:
    build:
      ./nginx
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8088:80
    depends_on:
      - apache