version: '3'

services:
  apache:
    build:
      ./httpd
    volumes:
      - ./src:/var/www/html
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./log:/var/log/httpd/
    depends_on:
      - php