version: '3'

services:
  apache:
    build:
      ./httpd
    volumes:
      - ./src:/var/www/html
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./log:/var/log/httpd/
    depends_on:
      - php

  nginx:
    build:
      ./nginx
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8088:80
    depends_on:
      - apache

  php:
    build:
      ./php
    volumes:
      - ./src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb

  mariadb:
    build:
      ./mariadb
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DBROOTPWD}
    logging:
      driver: none

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - mariadb:db
    ports:
      - 8765:80
    environment:
      - MYSQL_ROOT_PASSWORD=${DBROOTPWD}
    depends_on:
      - mariadb
    logging:
      driver: none
